# Generated by Django 5.1.6 on 2025-07-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_featuredblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredblog',
            options={'verbose_name_plural': 'Featured Blog'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published_at',
        ),
    ]
