# Generated by Django 5.1.6 on 2025-07-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_blog_created_at_blog_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-published_at',)},
        ),
    ]
