# Generated by Django 5.1.6 on 2025-03-23 08:35

import backend.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='uploads/projects/', validators=[backend.utils.validate_file_size, backend.utils.validate_image_extension])),
                ('skills', models.ManyToManyField(related_name='project_skills', to='skills.skill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_category', to='projects.projectcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
