# Generated by Django 5.1.6 on 2025-03-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
