# Generated by Django 5.1.6 on 2025-05-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_link_project_distinct_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
