# Generated by Django 5.1.6 on 2025-05-21 05:35

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/projects/banner_images/', validators=[backend.utils.validate_file_size, backend.utils.validate_image_extension]),
        ),
    ]
