# Generated by Django 5.1.6 on 2025-05-21 06:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
