# Generated by Django 5.1.6 on 2025-05-21 17:38

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='distinct_features',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Distinct Features'),
        ),
    ]
