# Generated by Django 5.1.6 on 2025-05-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_distinct_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
