# Generated by Django 5.1.6 on 2025-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_is_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
