# Generated by Django 5.1.6 on 2025-03-22 03:22

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(choices=[('fb', 'Facebook'), ('ig', 'Instagram'), ('be', 'Behance'), ('lkin', 'LinkedIn'), ('x', 'X'), ('gh', 'Github')], max_length=12, unique=True)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Media Link',
                'verbose_name_plural': 'Media Links',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile_pic/', validators=[backend.utils.validate_image_extension, backend.utils.validate_file_size]),
        ),
    ]
