# Generated by Django 5.1.6 on 2025-03-22 06:57

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_medialinks_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='uploads/resume/', validators=[backend.utils.validate_file_size, backend.utils.validate_pdf]),
        ),
    ]
