# Generated by Django 5.1.6 on 2025-05-21 05:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
