# Generated by Django 5.1.6 on 2025-05-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('appointment_datetime', models.DateTimeField()),
                ('alternative_datetime', models.DateTimeField(blank=True, null=True)),
                ('contact_number', models.CharField()),
                ('address', models.CharField(max_length=1000)),
                ('service', models.ManyToManyField(blank=True, null=True, related_name='service_appointment', to='services.service')),
            ],
            options={
                'verbose_name': 'Appointment Request',
                'verbose_name_plural': 'Appointment Requests',
            },
        ),
    ]
