# Generated by Django 5.1.6 on 2025-06-20 10:47

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/testimonials/image/', validators=[backend.utils.validate_image_extension, backend.utils.validate_file_size])),
                ('company', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=550)),
                ('testimonial', models.TextField()),
                ('to_publish', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestimonialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Testimonial Request',
                'verbose_name_plural': 'Testimonial Requests',
            },
        ),
    ]
