# Generated by Django 5.1.6 on 2025-06-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='order',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
