# Generated by Django 5.1.6 on 2025-06-23 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_testimonial_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('order',), 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
