# Generated by Django 5.1.6 on 2025-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0003_alter_testimonial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
