# Generated by Django 5.1.6 on 2025-03-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('company', models.CharField(max_length=1000)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('Onsite', 'ONSITE'), ('Remote', 'REMOTE'), ('Hybrid', 'HYBRID')], max_length=15)),
                ('skills', models.ManyToManyField(related_name='job_skills', to='skills.skill')),
            ],
        ),
    ]
