# Generated by Django 5.1.6 on 2025-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_options_experience_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_datetime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_datetime',
            field=models.DateField(),
        ),
    ]
