# Generated by Django 5.1.6 on 2025-03-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experience_end_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
