# Generated by Django 5.1.6 on 2025-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_rename_end_datetime_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='to_display',
            field=models.BooleanField(default=True),
        ),
    ]
